sudo: required
dist: trusty

services:
  - docker

install:
  - docker build --rm --file=Dockerfile --tag=rainbeam/eth-static .
  # create a container to copy files from (can't copy from an image)
  - tmp_container=$(docker create rainbeam/eth-static sh)
  - docker cp ${tmp_container}:/usr/local/bin/eth .
