sudo: required
dist: trusty

services:
  - docker

env:
  global:
    - secure: "ChnDfH9DxpHnGhtq5bj10ky4/1MKyzvqyfuE4aHY5YIUZfY+GxPVOw4zYzu5fXWLpSytGSIWLeG5XC7jrIHAiU37uCVKmiceXcggg5NxYAaoerQUWfp/TMzNikD5dvrU0KyFvdiHpf0axcPeuIeQ0Y35s8hNtXmQQWwYw2PmGJCWjdgbIx+vdy6kVsMpD7nlCo3PcbZh9EaeXfeYL4pPIDRYQa3zK1TQEsEo7Qa7rukKwN/8mCHcXSOeXYfYP57+qFNPK033sO9z4A6bl9wXj4IteBWIHCymYMCYZQA7oLbUp9gNcxytCSdjY6ap6yx8E+3y17BfLDkuXR1TuVgcGdww8js5q+rsfVCK3EbQbv+hZx4P9g6nNs1Jzl57c8lDCmMqcR/nrEmx9gzuvF3kxgxGeAxRXxvBnqKQoExCZc8tRbj2thUqG/wu6JePyJTUIval56pagqcd7dg8C42T/CNqzhiVcmoP80OxwM0O6+N4Ru8Is2HvBQQfddJ90gbEDU1oh5CYBNjHkWtu7OztlLqVcIQvpJMklPd086GebGy/d3+dNxCA4WTlcSq02J4epa+UKkwr/nLohW/lveHMD+7nPytEC7qFKlqf/6nro0BuR47cEN/UYVYBRTkjw1TlZpNFLUEQRbt/i0AkidN9HemaNb+HttR0Tvoc/5ICGi4="
    - secure: "MnR4YEWjUis/gT/Qnr9wKwSxDOFgO1tGvymxyIt0XpzULAseD3z9jxShi7d86cnA0DriQ9xoKw9P7FO48q6KLrL/Zlu7KZMJnBu1mTihmDQMYsFaMN0JdLDuEWgDuEfLa1IgDaIuSfYY+SlPLD7TJRzh1wEtSm+NB2TTLni2Js0T+guWf+bYgzHB4nIpaLG3k0p6zgo1j5qXE4oe1KoMD05eRp0gDTxxhAckSv0n9PLNDhxck3PqcHT9ZawRpWpWpLgT0v1JDbdYa/WWoeBXbrQUALj54FBXxKjYMSCRfhy3hN+LZ00huC1VX1oddKnS+kacoNWZhSnp1uv3rNZz+vLYrzGqDFZbCQ2OJu3wZRYDaIABdDQZcN9D2hH5n/6I4elx/jHrThW5AuN8LYxOlAoAxcHFetinSY1z4+wCLHd1ON7j+T+CEwBw1tR/yU2ZL6ZGFS8RIdJ0QKaleOqFGGOw7mTb00Bf7CdtNKIWjpZUdqvHq4FPVw45C4zKJ941wPQ6MvupDIlaa5+QoeWo1rzug+WzKdfCdq+KNwsGKmH3o3YXUhlSbTNw2afkJV5rKKBQbx7j7jBjqiOzmNYmsPBxv1dB4AGiL/3GV4qAtk1kBNuZ8P38NTEhHYf6hyW2Q04aIPPnaumz58HqJ4K7vIYyOB7dMUT+dvK+7d2OEk0="
    - secure: "nQl0deg66ezv0vrLNBX95s6920B2kquYvuOPmn7TZqMxIkn0WRxVLuI4/fIfC4XWieTk0IxqWOpd9vj3cueoZ6mhSFZ43C9unWIYB+q0dwUv040dTGjIq0x01G4lSarBFq2w2sTKfvsjprxiLQTZqCAiaQy+jTVtrlXE3RU/LjfEhcadjNf2g46IDQUji6ZSJVPynHGsorNQwtXvroz0ceAQSqANPdmpoo5ivrFqpW/s3sMeS5zerGTYaefhN6e/Oyk+1YWxmsYG4rLgwfG82MImNSjJ+6qvdsubi6Gb7msFiyv4uVH0K/MMTUILgstm1oo+YbeunSdnM5VjeddaeDP3jigH/CLylQ3tfwYrp52KrV5NCBtLeYGcP/cqj9eVM6KQj+HGoY8K2jjFpt5Ly3beVHZ7TMjb7+8CDai15zF+EnloJGpnPkoKUr022V3yJm9WJSCElaoy5KwDTgnQKiJO0mLV1zI3qm9ZdlM6sFEIgfeD3C1DhyQde076t8M9cM5Kj0sD6didtDtIhsBRHN5ezE9aCFVbkDgev8hWqoTVVUYtwB0x/vd6BHKE4hoFecejvXcloqjP+bjJQzRQLKzJ0aAnI6cSxoe8hlCfy/pPY/LgIYe+zoUNBMENs9hulAZXUUKnMbxV6iRA95AZQKxAhwtdwwr+OMuejNZELm8="

before_install:
  - docker pull rainbeam/eth-static || echo "ok"

install:
  - docker build --rm --file=Dockerfile --tag=rainbeam/eth-static .
  # create a container to copy files from (can't copy from an image)
  - tmp_container=$(docker create rainbeam/eth-static sh)
  - docker cp ${tmp_container}:/usr/local/bin/eth .

after_success:
  # trying to speed up build by caching the successful docker images
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - export REPO=rainbeam/eth-static
  - export COMMIT=${TRAVIS_COMMIT::8}
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      export TAG="latest"
      else export TAG=$TRAVIS_BRANCH
    fi
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
